      - name: Deploy to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          server-dir: ./
          log-level: standard

          exclude: |
            .htaccess
            **/.htaccess
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**
            **/vendor/**
            **/.env
            **/.env.*
            **/tests/**
            **/*.md
            **/storage/logs/**
            **/storage/framework/cache/**
            **/storage/framework/sessions/**
            **/storage/framework/views/**